name: Environmental Studies
type: major
degree: Bachelor of Arts
catalog: 2018-19

result:
  count: all
  of:
    - requirement: Major
    - requirement: Areas of Emphasis


requirements:
  Major:
    result:
      count: all
      of: [ENVST 137, ENVST 237, ENVST 399]


  Areas of Emphasis:
    save:
      - given: these requirements
        requirements:
          - requirement: Social Science
          - requirement: Arts and Humanities
        what: courses
        name: social and arts

      - given: these requirements
        requirements:
          - requirement: Natural Science
          - requirement: Arts and Humanities
        what: courses
        name: natural and arts

      - given: these requirements
        requirements:
          - requirement: Natural Science
          - requirement: Social Science
        what: courses
        name: natural and social

    result:
      count: any
      of:
        - both:
            - requirement: Natural Science
            - given: save
              save: social and arts
              what: courses
              do: count >= 3

        - both:
            - requirement: Social Science
            - given: save
              save: natural and arts
              what: courses
              do: count >= 3

        - both:
            - requirement: Arts and Humanities
            - given: save
              save: natural and social
              what: courses
              do: count >= 3


    requirements:
      Natural Science:
        result:
          count: all
          of:
            - requirement: Statistics, Modeling, and Mapping
            - requirement: Intermediate Chemistry
            - requirement: Intermediate Ecology
            - requirement: Environmental Science
            - requirement: Level III Natural Science

        requirements:
          Statistics, Modeling, and Mapping:
            result:
              count: 1
              of: [ENVST 255, STAT 212, STAT 272]

          Intermediate Chemistry:
            result:
              count: 1
              of:
                - both: [CHEM 248, CHEM 254]
                - both: [CHEM 255, CHEM 256]

          Intermediate Ecology:
            result:
              count: 1
              of: [BIO 261, BIO 226]

          Environmental Science:
            result:
              given: these courses
              courses:
                - ENVST 123
                - BI/ES 226
                - BI/ES 228
                - ENVST 245
                - ENVST 255
                - {course: ENVST 281, term: 2000-1}
                - BI/ES 286
                - BI/ES 250
                - {course: ENVST 381, term: 2000-1}
                - ENVST 397
                - BIO 224
              repeats: first
              limit:
                - where: {department: '! ENVST'}
                  at_most: 2
              what: courses
              do: count >= 2

          Level III Natural Science:
            result:
              count: 1
              of:
                - BI/ES 350
                - BIO 371
                - {course: BIO 391, term: 2000-1}
                - {course: CHEM 391, term: 2000-1}
                - {course: ENVST 391, term: 2000-1}

      Social Science:
        result:
          count: all
          of:
            - requirement: Methodological Analysis
            - requirement: Economic Analysis
            - requirement: Environmental Political Policy and Institutions
            - requirement: Social Science Electives

        requirements:
          Methodological Analysis:
            result:
              count: 1
              of:
                - ENVST 255
                - STAT 110
                - STAT 212
                - STAT 214
                - STAT 272
                - ECON 263
                - SOAN 371
                - PSYCH 230
                - PSCI 220

          Economic Analysis:
            result:
              count: all
              of:
                # todo: ECON 121 Principles of Economics (or ECON 110-ECON 120)  ???
                # what does it mean?
                - {count: any, of: [ECON 121, ECON 110, ECON 120]}
                - ECON 242

          Environmental Political Policy and Institutions:
            result:
              count: 1
              of: [ENVST 232, ES/PS 201, ES/PS 276]

          Social Science Electives:
            result:
              count: 2
              of:
                - ES/PS 201
                - ENVST 232
                - ENVST 235
                - ES/PS 276
                - {course: ENVST 281, term: 2000-1}
                - {course: ENVST 381, term: 2000-1}
                - {course: ENVST 396, term: 2000-1}
                - ECON 243
                - PSYCH 227
                - SOAN 247
                - {course: SOAN 297, term: 2000-1}
                - PSCI 221
                - SOAN 222
                - ID 234
                - AS/ES 227

      Arts and Humanities:
        result:
          given: these courses
          courses:
            - ENVST 202
            - ENVST 270
            - {course: ENVST 281, term: 2000-1}
            - {course: ENVST 381, term: 2000-1}
            - FILM 230
            - GERM 276
            - HIST 245
            - HIST 275
            - {course: NORW 224, term: 2000-1}
            - PHIL 257
            - ENGL 276
            - REL 278
            - ENVST 381
            - {course: DEPT 301, term: 2000-1}
          repeats: first
          limit:
            - {at_most: 5, where: {level: '200'}}
          what: courses
          do: count >= 6
